//  songs,artist,album,genre,time,

var music = [
["Auditorium","Mos Def","The Ecstatic","HipHop",274],
["Never Fallin","Living Legends","Classic","HipHop",323],
["Love Ain't","Cunninlynguists","SouthernUnderground","HipHop",240],
["Dysfunctional","Tech N9ne","Sickology 101","HipHop",244],
["Design in Malice","Jedi Mind Tricks","Violence Begets Violence","HipHop",235],
["Ms. Jackson","Outkast","Stankonia","HipHop",276],
["Hypnotize","Biggie Smalls","Life After Death","HipHop",231],
["Trying to Find A Balance","Atmosphere","Seven's Travels","HipHop",262],
["Acid Raindrops","People Under The Stairs","O.S.T.","HipHop",318],
["All Caps","Madvillain","Madvillainy","HipHop",134],
["Lone Digger","Caravan Palace","Robot Face","Electroswing",170],
["May Flowers","ProleteR","Curses from past times EP","Electroswing",269],
["MAMA YO!","Mayra Veronica vs. Yolanda Be Cool","Mama Yo!","Electroswing",248],
["Snake Charmer","Benny Berigan","Electro Swing, Vol. 2","Electroswing",304],
["All Night","Parov Stelar","The Princess Part One","Electroswing",165],
["Belle Belle","The Electric Swing Circus","The Electric Swing Circus","Electroswing",218],
["Istanbul","Milan & Phoenix","Istanbul (Single)","Electroswing",259],
["Liquid Lunch","Caro Emerald","Liquid Lunch (Single)","Electroswing",222],
["Bird's Lament","Moondog","DJ Kicks","Electroswing",324],
["1940","The Submarines","Honeysuckle Weeks","Electroswing",188],
["Home","Resonance","Odyssey","Vaporwave",212],
["420","Macintosh Plus","Floral Shoppe","Vaporwave",441],
["Memory","Creaetion","Memory (Single)","Vaporwave",126],
["Tuxedo Prince","Topaz Gang","Tuxedo Prince","Vaporwave",107],
["Honey","Id Chief","Honey (Single)","Vaporwave",175],
["We Bad","Childhood","We Bad (Single)","Vaporwave",225],
["Twenty Four Hour","Topaz Gang","Twenty Four Hour EP","Vaporwave",368],
["Party","Supersex 420","Party (Single)","Vaporwave",210],
["Cruiser","Esprit","Cruiser (Single)","Vaporwave",220],
["Weather Scanning","Lindsheaven Virtual Plaza","NTSC Memories","Vaporwave",261]
];